language: "en"

enable-emojis: true
emoji-list:
  - "Ä½"
  - "Ä¾"
  - "Ä¿"
  - "Å€"
  - "Å"
  - "Å‚"
  - "Åƒ"
  - "Å„"
  - "Å…"
  - "Å†"
  - "Å‡"
  - "Åˆ"
  - "Å‰"
  - "ÅŠ"
  - "Å‹"
  - "ğŸ’°"
  - "ğŸ‘€"
  - "ğŸ¤"